#Practical 8
 
Name: Shreyas Dongre   
Roll no: 082        
Division: I                         
Semester: 2nd Semester                                           
Batch: I3                                              
Experiment 8 - To study Set and Dictionary in Python.                                  
Date of Experiment: 15/4/2021

#Task 1                                       
Given dictionary items:                         
inventory = {
    'gold' : 500,
    'pouch' : ['flint', 'twine', 'gemstone'],
    'backpack' : ['xylophone','dagger', 'bedroll','bread loaf']
}

Perform Following tasks:                  
●	Add a key to inventory called 'pocket'.                  
●	Set the value of 'pocket' to be a list consisting of the strings 'seashell', 'strange berry', and 'lint'.                   
●	Sort items in the list stored under the 'backpack' key.                
●	Remove('dagger') from the list of items stored under the 'backpack' key.

In [ ]:
inventory = { 'gold' : 500, 'pouch' : ['flint', 'twine', 'gemstone'], 'backpack' : ['xylophone','dagger', 'bedroll','bread loaf'] }
print('Dict before:',inventory)

inventory['pocket'] = ['seashell','strange berry','lint']
inventory['backpack'].sort()
inventory['backpack'].remove('dagger')

print('Dict after:',inventory)

Dict before: {'gold': 500, 'pouch': ['flint', 'twine', 'gemstone'], 'backpack': ['xylophone', 'dagger', 'bedroll', 'bread loaf']}
Dict after: {'gold': 500, 'pouch': ['flint', 'twine', 'gemstone'], 'backpack': ['bedroll', 'bread loaf', 'xylophone'], 'pocket': ['seashell', 'strange berry', 'lint']}

# Task 2               
**a.**	Create a new dictionary called prices using these values.               
"Banana": 45                      
"Apple": 200                     
"Orange": 150                   
"Pear": 120                  

**b.**	Create a new dictionary called stock using these values.              
"Banana"= 6                 
"Apple"= 0               
"Orange" =32               
"Pear"= 15                


**c.**	For each key, print out the key along with its price and stock information. 
Print the answer in the following format:                   
apple                
price: 200               
stock: 0                


**d.**	Determine how much money you would make if you sold all of your food.       
Create a variable called total and set it to zero.               
For each key in prices, multiply the number in prices by the number in stock.                                                                       And find the total.

In [ ]:
# 2A
prices = {"Banana": 45,"Apple": 200,"Orange": 150,"Pear": 120}
print('Prices Dict: ',prices)

# 2B
stock = {"Banana": 6,"Apple": 0,"Orange": 32,"Pear": 15}
print('Stocks Dict: ',stock)

# 2C
for i in prices:
  print(i,':')
  print('price:',(prices[i]))
  print('stock:',(stock[i]))

# 2D
total = 0
for i in prices:
  res = prices[i]*stock[i]
  total += res

print('Total money made after selling everything:',total)

Prices Dict:  {'Banana': 45, 'Apple': 200, 'Orange': 150, 'Pear': 120}
Stocks Dict:  {'Banana': 6, 'Apple': 0, 'Orange': 32, 'Pear': 15}
Banana :
price: 45
stock: 6
Apple :
price: 200
stock: 0
Orange :
price: 150
stock: 32
Pear :
price: 120
stock: 15
Total money made after selling everything: 6870

#Task 3
a.	Create three dictionaries: lloyd, alice, and ritchie.              
b.	Give each dictionary the keys "name", "homework", "quizzes", and "tests".       
c.	Have the "name" key be the name of the student (that is, lloyd's name should be "Lloyd")                     
Example :  lloyd = {         
  "name": "Lloyd",             
  "homework": [90.0,97.0,75.0,92.0],          
  "quizzes": [88.0,40.0,94.0],           
  "tests": [75.0,90.0]      
}

In [ ]:
# 3A
lloyd={"name": "Lloyd","homework": [90.0,97.0,75.0,92.0],"quizzes": [88.0,40.0,94.0],"tests": [75.0,90.0]}
alice={"name": "Alice","homework": [92.0,91.0,72.0,89.0],"quizzes": [86.0,50.0,84.0],"tests": [79.0,80.0]}
ritchie={"name": "Ritchie","homework": [93.0,87.0,79.0,98.0],"quizzes": [78.0,60.0,99.0],"tests": [87.0,89.0]}

students = [lloyd,alice,ritchie]
for i in students:
  print(i['name'])
  print(i['homework'])
  print(i['quizzes'])
  print(i['tests'])

Lloyd
[90.0, 97.0, 75.0, 92.0]
[88.0, 40.0, 94.0]
[75.0, 90.0]
Alice
[92.0, 91.0, 72.0, 89.0]
[86.0, 50.0, 84.0]
[79.0, 80.0]
Ritchie
[93.0, 87.0, 79.0, 98.0]
[78.0, 60.0, 99.0]
[87.0, 89.0]

#3.1
Write a function average that takes a list of numbers and returns the average.                          
1.	Define a function called average that has one argument, numbers.
2.	Inside that function, call the built-in sum() function with the numbers list as a parameter.                                                           Store the result in a variable called total.
3.	Use float() to convert total and store the result in total.
4.	Divide total by the length of the numbers list. Use the built-in len() function to calculate that.Return that result.

In [ ]:
def average(numbers):
  total = sum(numbers)
  total = float(total)
  avg = total / (len(numbers))
  
  return avg


#3.2
Write a function called get_average that takes a student dictionary (like  lloyd, alice, and ritchie) as input and returns his/her weighted average.

In [ ]:
def get_average(student):
  homework = average(student["homework"])
  quizzes = average(student["quizzes"])
  tests = average(student["tests"])
  final = homework + quizzes + tests
  
  return final

#3.3 
Define a new function called get_letter_grade that has one argument called score. 
1.	Inside function, test score using a chain of if: / elif: / else: statements, like so:
2.	If score is 250 or above: return "A"               
Else if score is 200 or above: return "B"                   
Else if score is 150 or above: return "C"                     
Else if score is 100 or above: return "D"                  
Otherwise: return "F"               
3.	Finally, test your function. Call your get_letter_grade function with the result of get_average(lloyd). Print the resulting letter grade.

In [ ]:
def get_letter_grade(score):
  if score >= 250:
    return "A"
  elif score>=200:
    return "B"  
  elif score>=150:
    return "C"
  elif score>=100:
    return "D"
  else:
    return "F"      
  
print(get_letter_grade(get_average(lloyd)))

B

#Task 4  
Write a Python program to remove duplicates from the following dictionary    
Example :                   
Input: {'a': 'apple', 'b': 'banana', 'c': 'coconut', 'd': 'dragonfruit', 'e': 'apple', 'f': 'banana', 'g': 'guava'}               
Output:{'a': 'apple', 'b': 'banana', 'c': 'coconut', 'd': 'dragonfruit', 'g': 'guava'}

In [25]:
d1 = {'a': 'apple', 'b': 'banana', 'c': 'coconut', 'd': 'dragonfruit', 'e': 'apple', 'f': 'banana', 'g': 'guava'}

print('Input',d1)
c = []

f = dict()

for i,j in d1.items():
  if j not in c:
    c.append(j)
    f[i] = j

print('Output:',f)

Input {'a': 'apple', 'b': 'banana', 'c': 'coconut', 'd': 'dragonfruit', 'e': 'apple', 'f': 'banana', 'g': 'guava'}
Output: {'a': 'apple', 'b': 'banana', 'c': 'coconut', 'd': 'dragonfruit', 'g': 'guava'}

#Task 5  
Write a Python program to combine and create a dictionary from two other dictionaries by  adding their values for common keys.                     
Example :                     
Input:                 
D1 = {'apple': 1800, 'banana': 2500, 'coconut': 4300}             
D2 = {'apple': 3000, 'banana': 2000, 'grapes': 4000}               
Output:           
{'apple': 4800, 'banana': 4500, 'coconut': 4300, 'grapes': 4000}

In [ ]:
D1 = {'apple': 1800, 'banana': 2500, 'coconut': 4300}
D2 = {'apple': 3000, 'banana': 2000, 'grapes': 4000}

D3 = {}
D3.update(D1)
D3.update(D2)
for i in D2:
  if i in D1:
    D3[i] = D2[i] + D1[i]
  else:
    pass


D3

{'apple': 4800, 'banana': 4500, 'coconut': 4300, 'grapes': 4000}

#Task 6 
Write a Python program to create a dictionary from a string.                 
Input:                   
string: Programming                
Output: 
{'P': 1, 'r': 2, 'o': 1, 'g': 2, 'a': 1, 'm': 2, 'i': 1, 'n': 1}

In [24]:
string = "Programming"
dict1 = {}
for i in string:
  dict1[i] = dict1.get(i,0)+1
print(dict1)

{'P': 1, 'r': 2, 'o': 1, 'g': 2, 'a': 1, 'm': 2, 'i': 1, 'n': 1}

#Task 7
Write a program to input your friends names and their Phone Numbers and store them in the dictionary as the key-value pair. (take 5 key value pair)      
Perform the following operations on the dictionary:          
a) Display the name and phone number of all your friends         
b) Add a new key-value pair in this dictionary and display the modified dictionary            
c) Delete a particular friend from the dictionary            
d) Modify the phone number of an existing friend          
e) Check if a friend is present in the dictionary or not          
f) Display the dictionary in sorted order of names

In [ ]:
a = int(input('Enter the number of names to enter '))

names = {}
for i in range(a):
  name = input('Enter name ')
  num = int(input('Enter Phone number '))
  names[name] = num
print('Ans (A):',names)


names['Dream'] = 9836289762
print('Ans (B):',names)

del names['Dream']
print('Ans (C):',names)

for i in names:
  names[i] = 12345678
  break
print('Ans (D):',names)  


print('Ans (E):')
print("Pewds" in names)


print('Ans (F):')
for i in sorted(names):
  print((i,names[i]),end="")

Enter the number of names to enter 5
Enter name Shreyas
Enter Phone number 7738296515
Enter name Shrushti
Enter Phone number 88231234
Enter name Priyanka
Enter Phone number 82028264123
Enter name Pewds
Enter Phone number 6942096420
Enter name Pablo
Enter Phone number 8403782294
Ans (A): {'Shreyas': 7738296515, 'Shrushti': 88231234, 'Priyanka': 82028264123, 'Pewds': 6942096420, 'Pablo': 8403782294}
Ans (B): {'Shreyas': 7738296515, 'Shrushti': 88231234, 'Priyanka': 82028264123, 'Pewds': 6942096420, 'Pablo': 8403782294, 'Dream': 9836289762}
Ans (C): {'Shreyas': 7738296515, 'Shrushti': 88231234, 'Priyanka': 82028264123, 'Pewds': 6942096420, 'Pablo': 8403782294}
Ans (D): {'Shreyas': 12345678, 'Shrushti': 88231234, 'Priyanka': 82028264123, 'Pewds': 6942096420, 'Pablo': 8403782294}
Ans (E):
True
Ans (F):
('Pablo', 8403782294)('Pewds', 6942096420)('Priyanka', 82028264123)('Shreyas', 12345678)('Shrushti', 88231234)

#Task 8
Write a Python Program to Create a Dictionary with Key as First Character and Value as Words Starting with that Character.                        
Example:                    
Input:                
string: i love grapes guava watermelon pineapple pear mango            
Output:               
{'i': ['i'], 'l': ['love'], 'g': ['grapes', 'guava'], 'w': ['watermelon'], 'p': ['pineapple', 'pear'], 'm': ['mango']}

In [ ]:
string = 'i love grapes guava watermelon pineapple pear mango'

s1 = string.split()
dict1 = {}

for i in s1:
  if (i[0] not in dict1.keys()):
    dict1[i[0]] = []
    dict1[i[0]].append(i)
  else:
    if (i not in dict1[i[0]]):
      dict1[i[0]].append(i)
print(dict1)

{'i': ['i'], 'l': ['love'], 'g': ['grapes', 'guava'], 'w': ['watermelon'], 'p': ['pineapple', 'pear'], 'm': ['mango']}

#Task 9
List of participants in events A and B            
A → John, Olive,Alfie,Oscar,Ella,William,Harry.            
B → Edward, Julia, Robert, Olive,Alfie,Ella.            
1.	Find out which members attended both events.
2.	Find out which members attended only one of the events. **OMIT**
3.	Find out which members attended only one event and not the other.
4.	Receive a list of all participants

In [13]:
A = {'John', 'Olive', 'Alfie', 'Oscar', 'Ella', 'William', 'Harry'}
B = {'Edward', 'Julia', 'Robert', 'Olive', 'Alfie', 'Ella'}

#1
res = A.intersection(B)
print('Members who attended both the events are:',res)


#2 -  OMITTED


#3
res3 = A ^ B
print('Members who  attended ONLY one of the events are:',res3)


#4
res4 = A.union(B)
print('List of all participants:',list(res4))

Members who attended both the events are: {'Olive', 'Ella', 'Alfie'}
Members who  attended ONLY one of the events are: {'Robert', 'Oscar', 'John', 'Harry', 'William', 'Edward', 'Julia'}
List of all participants: ['Robert', 'Oscar', 'John', 'Ella', 'Olive', 'Harry', 'William', 'Edward', 'Julia', 'Alfie']

#Task 10
S1 = {'purple', 'red', 'blue', 'black',pink,’yellow’,’orange’,’white’}           
S2= {'yellow', 'orange', 'black',’purple’,’pink’,’brown’}            
S3 ={'pink', 'purple',’orange’}                
10.1 Write a Python Program to Check if a set is a subset of another set.      
10.2 Write a Python program to  Check if sets are superset of each other.

In [14]:
S1 = {'purple', 'red', 'blue', 'black','pink','yellow','orange','white'}
S2 = {'yellow', 'orange', 'black','purple','pink','brown'}
S3 = {'pink', 'purple','orange'}

In [21]:
#10.1
print('S1 =',S1)
print('S2 =',S2)
print('S3 =',S3)
print('\n')

print('Is S1 subset of S2?')
print(S1.issubset(S2))

print('Is S2 subset of S1?')
print(S2.issubset(S1))

print('Is S1 subset of S3?')
print(S1.issubset(S3))

print('Is S3 subset of S1?')
print(S3.issubset(S1))

print('Is S2 subset of S3?')
print(S2.issubset(S3))

print('Is S3 subset of S2?')
print(S3.issubset(S2))

S1 = {'black', 'orange', 'red', 'white', 'pink', 'blue', 'yellow', 'purple'}
S2 = {'black', 'orange', 'brown', 'pink', 'yellow', 'purple'}
S3 = {'pink', 'orange', 'purple'}


Is S1 subset of S2?
False
Is S2 subset of S1?
False
Is S1 subset of S3?
False
Is S3 subset of S1?
True
Is S2 subset of S3?
False
Is S3 subset of S2?
True

In [22]:
#10.2
print('S1 =',S1)
print('S2 =',S2)
print('S3 =',S3)
print('\n')

print('Is S1 superset of S2?')
print(S1.issuperset(S2))

print('Is S2 superset of S1?')
print(S2.issuperset(S1))

print('Is S1 superset of S3?')
print(S1.issuperset(S3))

print('Is S3 superset of S1?')
print(S3.issuperset(S1))

print('Is S2 superset of S3?')
print(S2.issuperset(S3))

print('Is S3 superset of S2?')
print(S3.issuperset(S2))

S1 = {'black', 'orange', 'red', 'white', 'pink', 'blue', 'yellow', 'purple'}
S2 = {'black', 'orange', 'brown', 'pink', 'yellow', 'purple'}
S3 = {'pink', 'orange', 'purple'}


Is S1 superset of S2?
False
Is S2 superset of S1?
False
Is S1 superset of S3?
True
Is S3 superset of S1?
False
Is S2 superset of S3?
True
Is S3 superset of S2?
False

#Conclusion:
1) Learnt the syntax and use of Dictionaries and Sets in Python.           
2) Used sort(),remove() etc. to sort/remove values from a key in dictionary.    
3) Created Empty Dictionary using Dict() function.                     
4) Used 'for' loop & dict.items() to traverse through dictionary.          
5) Operated on Sets using union(),intersection(),issubset(),issuperset() to find union,intersection,subsets and supersets respectively.           
6)  Used XOR operator to remove the same values from two sets.